services:
  base:
    build:
      context: ./base
      tags: 
        - "linhbngo/environments:base-latest"
  latex:
    build:
      context: ./latex
      tags: 
        - "linhbngo/environments:latex-latest"
    expose:
      - "8088"
    ports:
      - "18088:8088"
    volumes:
      - ../../:/data
    deploy:
      resources:
        limits:
          cpus: 2
